### ISSUE TITLE
add_renderer_globals

### ISSUE THREAD

**Issue by jvanasco** [Pylons/akhet#5]
you have this line:

```
request = event.get("request") or threadlocal.get_current_request()
if not request:
    return
```

have you ever encountered a situation where:
  a) event didn't have a request 
  b) threadlocal.get_current_request() was called
  c) there was not request ( the return statement )

i haven't been able to create this. i'm wondering what is / isn't necessary.

**Comment by mikeorr** [comment]
It's from the early days of Pyramid so may not be necessary now. The reason was that in some testing situations there may not be a request.

**Comment by jvanasco** [comment]
ah, testing.  thanks.

fwiw, I extended my implementation to have this bit of code in there:

```
if hasattr( request , 'subscriber_BeforeRender_add_renderer_globals' ):
    return
request.subscriber_BeforeRender_add_renderer_globals = True
```

it gives a quick exit to multiple calls on `BeforeRender` subscribers that are caused by pyramid_debugtoolbar
